application: chromusapp-v2
version: beta
runtime: python27
threadsafe: true
api_version: 1

handlers:
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /swf
  static_dir: swf

- url: /images
  static_dir: images

- url: /sm2_iframe
  static_files: sm2_iframe.html
  upload: sm2_iframe.html

- url: /chromus
  static_dir: chromus

- url: /.*
  script: main.app

builtins:
- datastore_admin: on