application: chromusapp
version: alpha
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /swf
  static_dir: swf

- url: /images
  static_dir: images

- url: /sm2_iframe
  static_files: sm2_iframe.html
  upload: sm2_iframe.html

- url: /.*
  script: chromus.py

- url: /_ah/warmup.*
  script: warmup.py

builtins:
- datastore_admin: on

inbound_services:
- warmup
