application: chromusapp
version: alpha
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /images
  static_dir: images

- url: /.*
  script: chromus.py

- url: /_ah/warmup.*
  script: warmup.py

builtins:
- datastore_admin: on

inbound_services:
- warmup
